FROM php:8.4-fpm-alpine

# Arguments for user
ARG UID=1000
ARG GID=1000

# Install system dependencies + Node.js + Chromium
RUN apk add --no-cache \
    git \
    curl \
    bash \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    libzip-dev \
    oniguruma-dev \
    icu-dev \
    libxml2-dev \
    linux-headers \
    nodejs \
    npm \
    chromium \
    libreoffice \
    fontconfig \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-dejavu \
    ttf-liberation \
    ttf-freefont

# PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
        pdo_mysql \
        mysqli \
        gd \
        zip \
        intl \
        mbstring \
        xml \
        bcmath \
        opcache \
        pcntl

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create user
RUN addgroup -g ${GID} appgroup \
    && adduser -u ${UID} -G appgroup -D -s /bin/bash appuser

# PHP dev settings
RUN echo "php_admin_value[error_reporting] = E_ALL" >> /usr/local/etc/php-fpm.d/www.conf \
    && echo "php_admin_flag[display_errors] = on" >> /usr/local/etc/php-fpm.d/www.conf \
    && echo "php_admin_flag[display_startup_errors] = on" >> /usr/local/etc/php-fpm.d/www.conf

# PHP config
RUN cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini" \
    && echo "memory_limit = 512M" >> "$PHP_INI_DIR/php.ini" \
    && echo "upload_max_filesize = 64M" >> "$PHP_INI_DIR/php.ini" \
    && echo "post_max_size = 64M" >> "$PHP_INI_DIR/php.ini" \
    && echo "max_execution_time = 300" >> "$PHP_INI_DIR/php.ini"

WORKDIR /var/www/html

# Entry point
COPY --chmod=755 docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

RUN chown -R appuser:appgroup /var/www/html

# Set environment variable for Browsershot to find Chromium
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
ENV SOFFICE_PATH=/usr/bin/soffice

# instaliraj jebeni puppeteer
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
RUN npm install -g puppeteer

USER appuser

EXPOSE 9000

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["php-fpm"]
